### ISSUE TITLE
Second Warning 

### ISSUE THREAD

**Issue by AssaEmpireToken** [parames3010/PancakeswapPredictionBot-2022#4]
We, the AssaEmpire/SavannahCat team, urge you to modify your readme. You have copied our readme 1 to 1. If there is no reaction, we still have your contact details, so that we will take legal action against it. We hereby ask you to create your own readme.

We have currently informed our lawyer and Github.
If nothing comes, your account will be blocked because of the violation.

Wir das AssaEmpire/SavannahCat team fordern sie hiermit auf ihre Readme abzuändern. Sie haben unsere Readme 1 zu 1 Kopiert. Sollte keine Reaktion kommen haben wir immerhin ihre Kontaktdaten, so das wir dagegen anwaltlich gegen vorgehen werden. Wir bitten sie hiermit auf ihre eigene Readme zu erstellen.

Aktuell haben wir unseren Anwalt davon informiert und Github.
Sollte nichts kommen wir ihr account gesperrt wegen des Verstoßes.

**Comment by parames3010** [comment]
Okay

**Comment by AssaEmpireToken** [comment]
If you want, we can also have our lawyer write to you.

**Comment by AssaEmpireToken** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">



<url>
  <loc>https://www.assaempire.eu/</loc>
  <lastmod>2022-01-07T00:16:54+00:00</lastmod>
  <priority>1.00</priority>
</url>
<url>
  <loc>https://www.assaempire.eu/index.html</loc>
  <lastmod>2022-01-07T00:16:54+00:00</lastmod>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://www.assaempire.eu/savannah.html</loc>
  <lastmod>2022-01-07T00:16:54+00:00</lastmod>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://www.assaempire.eu/roadmap.html</loc>
  <lastmod>2022-01-07T00:16:54+00:00</lastmod>
  <priority>0.80</priority>
</url>


</urlset>


this Is my copy !!!
